# config_template.yaml

# Installation section
# Fields:
#   - name: Name of the tool (required)
#   - method: Installation method, e.g., 'brew' for Homebrew formula or 'cask' for Homebrew Cask (optional)
#   - install_command: Custom command to install the tool (optional)
#   - post_install: List of commands to run after installation (optional)
tools:
  - name: "example_tool_name"
    # install_command: "custom_command_to_install_tool"  # Uncomment and replace if needed
    post_install:
      - "echo 'export PATH=/path/to/example_tool/bin:$PATH' >> ~/.zshrc"
      - "source ~/.zshrc"
      - "example_tool_name --version" # Optional: verify installation

  - name: "another_tool"
    method: "cask"
    post_install:
      - "echo 'export ANOTHER_TOOL_HOME=/Applications/AnotherTool.app' >> ~/.zshrc"
      - "source ~/.zshrc"

# Configuration section
# Fields:
#   - name: Name of the tool to configure (required)
#   - config_url: URL to the configuration file (required)
#   - install_path: Path where the configuration should be installed (required)
configure:
  - name: "neovim"
    config_url: "https://github.com/example/neovim-config/raw/main/init.vim"
    install_path: "~/.config/nvim/init.vim"

  # Add more tools to configure as needed, following the same structure
