tools:
  - name: "neovim"    # Will use Homebrew by default
  - name: "alacritty"
    method: "cask"    # Specifies this is a Homebrew cask
  - name: "uv"
    install_command: "curl -LsSf https://astral.sh/uv/install.sh | sh"
