# template.yaml
# Use this template to define tools for installation.
# Fill out the details according to the specifications below.
#
# Fields:
#   - name: Name of the tool (required)
#   - method: Installation method, e.g., 'cask' for Homebrew Cask (optional)
#   - install_command: Custom command to install the tool (optional)

tools:
  - name: "example_tool_name" # Replace 'example_tool_name' with the actual tool name.
    # method: "cask"            # Uncomment if this tool should be installed as a Homebrew cask.
    # install_command: "custom_command_to_install_tool"  # Uncomment and replace with the actual install command if a custom method is needed.
