name: Lint
on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum

env:
  GO111MODULE: on
  
jobs:
    golangci-lint:
      runs-on: ubuntu-latest
      steps:
  
        - uses: actions/setup-go@v2
          with:
            go-version: '1.21'
  
        - uses: actions/checkout@v3.1.0
  
        - uses: golangci/golangci-lint-action@v6
          with:
            version: latest
            args: --verbose
